//Employees Constants
export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST";
export const GET_EMPLOYEES = "GET_EMPLOYEES";

export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEE = "GET_EMPLOYEE";

export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";

export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

//Feedback Constants
export const GET_FEEDBACKS_REQUEST = "GET_FEEDBACKS_REQUEST";
export const GET_FEEDBACKS = "GET_FEEDBACKS";

export const GET_FEEDBACK_REQUEST = "GET_FEEDBACK_REQUEST";
export const GET_FEEDBACK = "GET_FEEDBACK";

export const ADD_FEEDBACK_REQUEST = "ADD_FEEDBACK_REQUEST";
export const ADD_FEEDBACK = "ADD_FEEDBACK";

export const UPDATE_FEEDBACK_REQUEST = "UPDATE_FEEDBACK_REQUEST";
export const UPDATE_FEEDBACK = "UPDATE_FEEDBACK";

//User Constants
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS";

//Errors
export const GET_ERRORS = "GET_ERRORS";
